<?php

namespace AppBundle\Repository;

/**
 * DemoERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemoERepository extends \Doctrine\ORM\EntityRepository
{
}
