<?php

namespace AppBundle\Repository;

/**
 * MatchDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
