<?php

namespace AppBundle\Repository;

/**
 * TournamentRankingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentRankingRepository extends \Doctrine\ORM\EntityRepository
{
}
