<?php

namespace AppBundle\Repository;

/**
 * TournamentGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentGroupRepository extends \Doctrine\ORM\EntityRepository
{

}
