<?php

namespace AppBundle\Repository;

/**
 * TournamentFinalRoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentFinalRoundRepository extends \Doctrine\ORM\EntityRepository
{
}
