<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

  public function findByList($role = null)
  {
    $qb =  $this
          ->createQueryBuilder('u')
          ->leftJoin('u.person', 'p')
          ->orderBy('p.lastname', 'ASC')
          ->where('u.isActive = 1');
    if($role != null) {
      $qb->andWhere('u.roles like :role')
      ->setParameter(':role', '%'.$role.'%');
    }
    return $qb
          ->getQuery()
          ->getResult()
          ;
  }

  public function findLike($role, $search) {
    return $this
          ->createQueryBuilder('u')
          ->leftJoin('u.person', 'p')
          ->orderBy('p.lastname', 'ASC')
          ->where('u.isActive = 1')
          ->andWhere('p.firstname like :search OR p.lastname like :search')
          ->andWhere('u.roles like :role')
          ->setParameter(':role', '%'.$role.'%')
          ->setParameter(':search', '%'.$search.'%')
          ->getQuery()
          ->getResult()
          ;
  }

  public function findByEmail($email) {
    return $this
          ->createQueryBuilder('u')
          ->where('u.email = :email')
          ->setParameter(':email', $email)
          ->getQuery()
          ->getOneOrNullResult()
          ;
  }


}
