# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    providers:
        in_memory:
            memory: ~
        main:
            entity:
                class: AppBundle\Entity\User
                property: email

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        AppBundle\Entity\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: dashboard
            logout:
                path:   logout
                target: homepage
